summary: Update arch linux image in google account

systems: [arch-linux-64-base]

environment:
    TARGET_SYSTEM: arch-linux-64

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # remove the user account that was present in the base image
        userdel -r -f alrii14344 || true

        # Fix shadow.service by creating missing home dirs for users
        if [ ! -d /home/user ]; then
            mkdir -p /home/user
            chown -R user:user /home/user
            mkdir -p /home/guest
            chown -R guest:guest /home/guest
            systemctl restart shadow.service
        fi

        # Make the upgrade
        distro_update_package_db
        distro_upgrade_packages
        install_test_dependencies "$TARGET_SYSTEM"
        remove_pkg_blacklist

        # since 4.16, kernel crng init can take significant time, thus services
        # depending on crypto such as sshd will take longer to start
        distro_install_package haveged
        systemctl enable --now haveged

        REBOOT
    fi

    # Install the new version os gce packages    
    curl -L -o /tmp/pkgbuilds.tar.gz https://github.com/bboozzoo/pkgbuilds/archive/master.tar.gz
    tar -C /tmp/ -xvf /tmp/pkgbuilds.tar.gz
    cd /tmp/pkgbuilds-master/google-compute-engine

    useradd -p ubuntu test
    chown test:test /tmp/pkgbuilds-master/google-compute-engine
    su -c 'makepkg' test
    distro_purge_package gce-compute-image-packages
    pacman --noconfirm -U /tmp/pkgbuilds-master/google-compute-engine/*.pkg.tar.xz
    userdel test
    rm -rf /tmp/pkgbuilds-master/

    #distro_install_google_compute_engine
    # Disable google-shutdown-scripts service because it hungs during reboot
    systemctl disable --now google-shutdown-scripts.service

    # Enable apparmor
    if ! MATCH "apparmor=1" < /etc/default/grub; then
        distro_install_package apparmor
        systemctl enable apparmor
        sed -e 's/GRUB_CMDLINE_LINUX="/GRUB_CMDLINE_LINUX="apparmor=1 security=apparmor /g' -i /etc/default/grub
        grub-mkconfig -o /boot/grub/grub.cfg
    fi

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
