summary: Update Linode image.

execute: |
    case "$SPREAD_SYSTEM" in
        fedora-*)
            dnf upgrade -y
            dnf autoremove -y
            ;;
        ubuntu-*|debian-*)
            case $SPREAD_REBOOT in

            0)

                uname -r > old-kernel

                # apt update is hanging on security.ubuntu.com with IPv6.
                sysctl -w net.ipv6.conf.all.disable_ipv6=1
                apt update
                apt dist-upgrade -y
                sysctl -w net.ipv6.conf.all.disable_ipv6=0

                REBOOT
                ;;

            1)

                # Remove old kernel.
                old_kernel=$(cat old-kernel)
                new_kernel=$(uname -r)
                if [ $new_kernel != $old_kernel ]; then
                    apt remove -y $(dpkg -S /boot/vmlinuz-$old_kernel | sed 's/:.*//')
                fi

                # Ensure single kernel remains.
                if ! ls /boot/vmlinuz-* | wc -l | grep '^1$'; then
                    echo "Unused kernels remain:"
                    ls /boot/vmlinuz-*
                    exit 1
                fi

                ;;

            esac
            ;;
        *)
            echo "ERROR: system $SPREAD_SYSTEM is not yet supported"
            exit 1
            ;;
    esac
