summary: Update fedora base image with the latest updates

systems: [fedora-rawhide-64]

environment:
    TARGET_SYSTEM: fedora-rawhide-64

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Normalize fedora base url among fedora versions
        sed -i -s -E -e 's@^#?baseurl=http://download.example/@#baseurl=http://download.fedoraproject.org/@g' /etc/yum.repos.d/fedora*.repo

        # The Fedora archive mirror seems to be unreliable.
        # Switch to the main archive by commenting out metaink and uncommenting baseurl
        sed -i -s -E -e 's@^#?baseurl=http://download.fedoraproject.org/@baseurl=http://dl.fedoraproject.org/@g' -e 's@^metalink=@#metalink@g' /etc/yum.repos.d/fedora*.repo
        dnf --refresh -y makecache

        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db
        distro_upgrade_packages

        # Disable google-network-daemon service because it conflicts with spread ssh configuration during startup
        systemctl disable --now google-network-daemon.service || true

        # Disable cloud init because reset sshd config affecting spread metadata script
        # Also in fedora 29 cloud-init fails on start
        touch /etc/cloud/cloud-init.disabled

        REBOOT
    fi

    # Purge old kernel-core package and install kernel modules
    distro_clean_old_packages kernel-core
    distro_install_package kernel-modules

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    
    delete_snapshot "$DISK"
    delete_deprecated_images