summary: Update fedora base image with the latest updates

systems: [fedora-rawhide-64]

environment:
    TARGET_SYSTEM: fedora-rawhide-64

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        distro_update_package_db
        distro_upgrade_packages

        # Disable google-network-daemon service because it conflicts with spread ssh configuration during startup
        systemctl disable --now google-network-daemon.service || true

        # Disable cloud init because reset sshd config affecting spread metadata script
        # Also in fedora 29 cloud-init fails on start
        touch /etc/cloud/cloud-init.disabled

        REBOOT
    fi

    # Purge old kernel-core package
    pkgs=$(rpm -qa kernel-core)
    if [ $(echo "$pkgs" | wc -w) -gt 1 ]; then
        pkg=$(echo $pkgs | cut --delimiter " " --fields 2)
        distro_purge_package "$pkg"
    fi

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    
    delete_snapshot "$DISK"
    delete_deprecated_images