summary: Add opensuse tumbleweed base image with the latest updates

systems: [opensuse-15.2-64-base]

environment:
    TARGET_SYSTEM: opensuse-tumbleweed-64-base

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Remove the existing repos
        mkdir /etc/zypp/repos.d/old
        mv /etc/zypp/repos.d/*.repo /etc/zypp/repos.d/old

        # Add tumbleweed repos
        zypper ar -f -c http://download.opensuse.org/tumbleweed/repo/oss repo-oss
        zypper ar -f -c http://download.opensuse.org/tumbleweed/repo/non-oss repo-non-oss
        zypper ar -f -c http://download.opensuse.org/tumbleweed/repo/debug repo-debug
        zypper ar -f -c http://download.opensuse.org/update/tumbleweed/ repo-update

        zypper addrepo https://download.opensuse.org/repositories/Cloud:Tools/openSUSE_Tumbleweed/Cloud:Tools.repo

        # Make the upgrade and install the dependencies needed to run snapd tests
        zypper --gpg-auto-import-keys refresh

        distro_install_package google-guest-agent
        zypper --gpg-auto-import-keys dup -y || true
        remove_pkg_blacklist
        distro_clean_package_cache

        REBOOT
    fi

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images