summary: Update opensuse 16.0 64 bits image with the latest updates and test dependencies

systems: [opensuse-16.0-64-base]

environment:
    TARGET_SYSTEM: opensuse-16.0-64

execute: |
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Cleanup repos
        rm -f /etc/zypp/repos.d/*.repo
        cp leap16.repo /etc/zypp/repos.d/

        # Make the upgrade and install the dependencies needed to run snapd tests
        # In case some repo cannot be updated due to proxy restriction
        distro_update_package_db
        distro_upgrade_packages || true

        install_pkg_dependencies
        install_test_dependencies "$TARGET_SYSTEM"

        # see (applies to TW as well): https://en.opensuse.org/How_to_switch_from_SELinux_to_AppArmor_in_Leap_16
        # install AppArmor tools
        zypper in -y --type pattern apparmor

        sed -i -e 's/security=selinux/security=apparmor/g' -e 's/selinux=1//g' /etc/default/grub
        update-bootloader

        remove_pkg_blacklist

        REBOOT
    fi

    # confirm that AppArmor is enabled
    aa-enabled

    # and selinux is disabled
    ! selinuxenabled

    # Setup ntp server depending on the openstack environment
    update_ntp

    # Clean the disk
    clean_machine

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"
    sync
