summary: Update Ubuntu 26.04 64 bits image with the latest updates

systems: [ubuntu-26.04-64-base]

environment:
    TARGET_SYSTEM: ubuntu-26.04-64

execute: |
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    # Remove this kernel downgrade when the 6.19 kernel gets fixed
    if [ "$SPREAD_REBOOT" = 0 ]; then

        distro_update_package_db

        apt install -y linux-image-6.17.0-8-generic
        apt install -y linux-headers-6.17.0-8-generic

        sed -i 's/^GRUB_DEFAULT/# &/' /etc/default/grub
        sh -c 'printf "GRUB_SAVEDEFAULT=true\nGRUB_DEFAULT=saved\n" >> /etc/default/grub'
        update-grub
        grub-set-default "Advanced options for Ubuntu>Ubuntu, with Linux 6.17.0-8-generic"
        update-grub

        REBOOT
    fi

    if [ "$SPREAD_REBOOT" = 1 ]; then
        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db
        distro_upgrade_packages

        install_pkg_dependencies
        install_test_dependencies "$TARGET_SYSTEM"

        remove_pkg_blacklist

        REBOOT
    fi

    # Avoid checking for new release, it could cause lock on apt
    sed -i 's/^Prompt=.*$/Prompt=never/' /etc/update-manager/release-upgrades

    # Disable daily checks for updates to avoid apt locks
    sudo systemctl disable --now apt-daily{,-upgrade}.{timer,service}

    # Disable the service because sometimes is failing
    systemctl disable --now fwupd.service fwupd-refresh.service fwupd-refresh.timer

    # Setup ntp server depending on the openstack environment
    update_ntp

    # Clean disk before create the shapshot
    clean_machine

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"
    sync
